### ISSUE TITLE
Batch Shipyard configuration files

### ISSUE THREAD

**Issue by mesnardo** [richardlock/docker-openfoam6-paraview54-intelmpi#1]
Hello @richardlock,

Thank you for creating a Docker image with OpenFOAM-6.
I saw (in an [issue](https://github.com/Azure/batch-shipyard/issues/277) on Batch Shipyard repo) that you have been able to run jobs with this image on H16r nodes.
Would you mind sharing the YAML configuration files you used to create the pool and submit jobs? (As well as the bash script used to setup directories and source OpenFOAM.)

Thanks!

**Comment by richardlock** [comment]
Hi @mesnardo,

I'm happy to share my config files for this.  I will email this over to you.  It's a good while since I did any work on this in Batch Shipyard so things may have moved on now, but happy to share what I can.

Thanks, Richard

**Comment by mesnardo** [comment]
Thank you @richardlock for sharing! This is very helpful!
